title: WikiFinancepedia theme
logo: /assets/img/WikiFinancepedia-Wikipedia-of-Finance.png
description: WikiFinancepedia - A Wikipedia of Finance
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
